name: Publish to StreamX

on:
  repository_dispatch:
    types:
      - resource-published
jobs:
  check-event-status:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"

  publish-to-streamx:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204) && endsWith(github.event.client_payload.path, '.md')
    runs-on: ubuntu-latest
    steps:
      - name: Publish to StreamX
        run: |
          sleep 1s
          PAGE_PATH=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
          EDS_PAGE_URL="${{ vars.EDS_DOMAIN_URL }}$PAGE_PATH"
          echo "Page URL: $EDS_PAGE_URL"
          pageHtml=$(curl -s $EDS_PAGE_URL | jq . -sR)
          echo "Page HTML: $pageHtml"
          streamxResponse=$(curl -i -X PUT ${{ vars.STREAMX_PAGE_PUBLICATION_API }}$PAGE_PATH.html -H "Authorization: Bearer ${{ secrets.STREAMX_TOKEN }}" -H 'Content-Type: application/json' -d "{\"content\": {\"bytes\": $pageHtml}}")
          echo -e "StreamX response:\n$streamxResponse"
        shell: bash
