name: Unpublish from StreamX

on:
  repository_dispatch:
    types:
      - resource-unpublished
jobs:
  check-event-status:
    runs-on: ubuntu-latest
    steps:
      - env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: |
          echo $CLIENT_PAYLOAD
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"

  unpublish-from-streamx:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204) && endsWith(github.event.client_payload.path, '.md')
    runs-on: ubuntu-latest
    steps:
      - name: Unpublish from StreamX
        run: |
          sleep 1s
          PAGE_PATH=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
          streamxKey=${{ vars.STREAMX_PAGE_PUBLICATION_API }}${{ vars.STREAMX_KEY_PREFIX }}$PAGE_PATH
          echo "StreamX URL: $streamxKey"
          streamxResponse=$(curl -i -X DELETE $streamxKey \
            -H "Authorization: Bearer ${{ secrets.STREAMX_TOKEN }}")
          echo -e "StreamX response:\n$streamxResponse"
        shell: bash
        