name: Unpublish from StreamX

on:
  repository_dispatch:
    types:
      - resource-unpublished
jobs:
  check-event-status:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"

  publish-to-streamx:
    if: (github.event.client_payload.status == 200 || github.event.client_payload.status == 204) && endsWith(github.event.client_payload.path, '.md')
    runs-on: ubuntu-latest
    steps:
      - name: Unpublish from StreamX
        run: |
          sleep 1s
          PAGE_PATH=$(echo "${{ github.event.client_payload.path }}" | sed 's/\.md$//g')
          streamxResponse=$(curl -i -X DELETE ${{ vars.STREAMX_PAGE_PUBLICATION_API }}$PAGE_PATH.html -H "Authorization: Bearer ${{ secrets.STREAMX_TOKEN }}")
          echo -e "StreamX response:\n$streamxResponse"
        shell: bash
        