name: Publish web resource to StreamX

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: run_on_pr_merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Modified files
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.pull_request)

            const { execSync } = require('child_process')
            const { commits } = context.payload.pull_request
            const rawFiles = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
            const files = rawFiles.split('\n').filter(Boolean)

            console.log(files)