name: Publish web resource to StreamX

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish-if-merged:
    if: github.event.pull_request.merged == true
    name: run_on_pr_merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Publish modified files to StreamX
        run: |
          sleep 1s
          DRY_RUN=${{ vars.DRY_RUN == 'true' ? true : false }}
          if $DRY_RUN; then
            echo "Dry run mode: enabled"
          fi
          PUBLISH_STREAMX_FILES_PATTERNS=${{ vars.PUBLISH_STREAMX_FILES_PATTERNS}}
          if [[ ! "$PUBLISH_STREAMX_FILES_PATTERNS" ]]; then
            echo "Missing file patterns variable [PUBLISH_STREAMX_FILES_PATTERNS]. Execution skipped."
            exit 1;
          fi
          echo "Accepted file patterns: $PUBLISH_STREAMX_FILES_PATTERNS"
          echo "--------------------------------------"
          console.log(context.payload.pull_request)

          const { execSync } = require('child_process')
          const { commits } = context.payload.pull_request
          const rawFiles = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
          const files = rawFiles.split('\n').filter(Boolean)

          console.log(files)
          for file in $files; do
            echo "$file was changed"
            for pattern in $PUBLISH_STREAMX_FILES_PATTERNS; do
              echo "$pattern verification"
            done
          done

        shell: bash