name: Publish web resource to StreamX

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  publish-if-merged:
    if: github.event.pull_request.merged == true
    name: run_on_pr_merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Publish modified files to StreamX
        run: |
          VARS_PUBLISH_STREAMX_FILES_PATTERNS='${{ vars.PUBLISH_STREAMX_FILES_PATTERNS }}';
          VARS_DRY_RUN='${{ vars.DRY_RUN }}';

          if [[ -z $VARS_PUBLISH_STREAMX_FILES_PATTERNS && $VARS_PUBLISH_STREAMX_FILES_PATTERNS == ""  ]]; then
            echo "Missing file patterns variable [PUBLISH_STREAMX_FILES_PATTERNS]. Execution skipped.";
            exit 1;
          fi

          sleep 1s
          DRY_RUN=false;
          if [[ ! -z $VARS_DRY_RUN && $VARS_DRY_RUN == "true" ]]; then
            DRY_RUN=true;
            if ( $DRY_RUN ); then
              echo "Dry run mode: enabled"
              echo "--------------------------------------"
            fi
          fi

          patterns=`echo "$VARS_PUBLISH_STREAMX_FILES_PATTERNS" | jq .[]`
          echo "Accepted file patterns:"
          echo "$patterns"
          echo "--------------------------------------"

          echo "--------------------------------------"
          echo "--------------------------------------"
          echo "${{ github.event.pull_request.commits }}"
          echo "--------------------------------------"
          echo "--------------------------------------"

          changed_files=$(`git diff --name-only HEAD HEAD~"${{ github.event.pull_request.commits }}"`)

          for file in $changed_files; do
            echo "$file was changed"
            for pattern in $patterns; do
              echo "Checking $file for pattern $p";
            done
          done

        shell: bash